#!/usr/bin/env sh

ex_file=`mktemp`
graft="0"
master="0"
obsolete="0"
exclude="HEAD"
gc="0"

help() {
	echo 'Usage:'
	echo '  git-prune -g=starting_commit_hash [ -o=reference_commit_hash ] [ -m=new_master_branch ] [ -e=exclude_branches ] [ -c ]'
	echo '    -g - commit hash to remove history before'
	echo '    -o - commit hash to check branches against'
	echo '    -m - name of the branch to create new master from'
	echo '    -e - comma-separated list of branches to be excluded from repository'
	echo '    -c - perform aggressive garbage collection'
	echo
}

header() {
	echo
	echo '========================================'
	echo $1
	echo '========================================'
}

parse_args() {
	for arg in $@; do
		case $arg in
			-g=*)
				graft="${arg#*=}"
				shift
				;;
			-o=*)
				obsolete="${arg#*=}"
				shift
				;;
			-m=*)
				master="${arg#*=}"
				shift
				;;
			-e=*)
				exclude="${arg#*=}"
				shift
				;;
			-c)
				gc="1"
				shift
				;;
			*)
				shift
				;;
		esac
	done
}

validate_args() {
	if [ "$1" = "0" ]; then
		help
		echo 'No graft provided'
		exit
	fi
}

actualize_repo() {
	git fetch --prune --all
	git reset --hard --quiet
}

recreate_master() {
	git checkout $1
	git branch -D master
	git checkout -b master
}

sync_branches() {
	for remote in `git branch --remote | grep -v "/HEAD"`; do
		remote=`echo ${remote} | sed 's/ *//g'`;
		local=`echo "${remote}" | cut -d "/" -f 2`
		is_ex=`grep -x "${remote}" $ex_file`
		if [ -n "${is_ex}" ]; then
			echo "${remote} is skipped..."
		else
			echo "${remote} -> ${local}"
			git checkout --quiet $local
			git reset --hard --quiet $remote
		fi
	done
	git checkout master
	git reset --hard
}

collect_obsolete_branches() {
	backup_ifs=$IFS
	IFS=','
	exes=$3
	for branch in $exes; do
		echo "origin/${branch}" >> $ex_file
	done
	IFS=$backup_ifs

	if [ "$2" != "0" ]; then
		git branch --remote --contains $obsolete | grep -v "/HEAD" | sed 's/ *//g' >> $ex_file
	else 
		all=`mktemp`
		act=`mktemp`
		git branch --remote | sort | sed 's/ *//g' > $all
		git branch --remote --contains $1 | sort | sed 's/ *//g' > $act
		comm -3 $all $act >> $ex_file
		rm $all $act
	fi
	cat $ex_file
}

filter_history() {
	git filter-branch --force --tag-name-filter cat -- --all
	rm .git/info/grafts
	# remove filter-branch backup 
	git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
	git reflog expire --expire=now --all
}

parse_args $@
validate_args $graft $obsolete $master $exclude $gc

header 'Actualizing repo...'
actualize_repo

if [ "$master" != "0" ]; then
	header 'Recreating master...'
	recreate_master $master
fi

header 'Creating graft...'
echo $graft > .git/info/grafts

header 'Collecting obsolete branches...'
collect_obsolete_branches $graft $obsolete $exclude

header 'Syncing remote branches...'
sync_branches

header 'Removing origin...'
git remote rm origin

header 'Filtering history...'
filter_history

if [ "$gc" != "0" ]
then
	header 'Collecting garbage...'
	git gc --prune=now --aggressive
fi

rm $ex_file

header 'Done'
